debug:
  true

server:
  port: 8080

spring:
  http:
    encoding:
      enabled: true
      charset: utf-8
      force: true
  profiles:
    active: dev

  thymeleaf:
    cache: false

  messages:
    basename: static.i18n.login
